import puppeteer from "puppeteer";

export async function generatePDFWithTailwind(htmlTableContent: string) {
  const browser = await puppeteer.launch({
    headless: true,
    args: ["--no-sandbox", "--disable-setuid-sandbox"],
  });

  const page = await browser.newPage();

  const fullHTML = `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>PDF Report</title>
  <script src="https://cdn.tailwindcss.com"></script>
   <style>
   @page {
    size: A4;
    margin: 0;
   }
          table {
            width: 100%;
            border-collapse: collapse;
            font-family: Arial, sans-serif;
            font-size: 12px;
          }
          th, td {
            border: 1px solid #ccc;
            padding: 6px 8px;
            text-align: center;
          }
          th {
            background-color: #F3F3F3;
          }
          .status-button {
            padding: 4px 8px;
            border-radius: 4px;
            font-size: 11px;
            text-transform: uppercase;
            border: none;
          }
          .status-button.approved {
            background-color: #D4EDDA;
            color: #155724;
          }
          .status-button.rejected {
            background-color: #F8D7DA;
            color: #721C24;
          }
          .status-button.pending {
            background-color: #FFF3CD;
            color: #856404;
          }
        </style>
</head>
<body class="p-8 text-black">

  
  <div class="w-full h-[100vh] flex flex-col justify-center items-center text-center">
    <img src=/images/google.png" alt="Logo" class="w-32 h-auto mb-6" />
    <h1 class="text-4xl font-bold mb-4">Google Keyword Ranking Report</h1>
    <h2 class="text-xl mb-2 text-gray-700">Campaign: July 2025</h2>
    <p class="text-md text-gray-600">Generated by Company</p>
  </div>

 

  <!-- TABLE PAGE -->
  <div>
    <h2 class="text-xl font-semibold mb-4">Detailed Keyword Report</h2>
    ${htmlTableContent}
  </div>

</body>
</html>
`;

  await page.setContent(fullHTML, { waitUntil: "networkidle0" });

  const pdf = await page.pdf({
    format: "A4",
    printBackground: true,
    margin: { top: "1cm", bottom: "1cm", left: "1cm", right: "1cm" },
  });

  await browser.close();
  return pdf;
}
