import React from "react";

const TermsAndConditions: React.FC = () => {
  return (
    <div className="max-w-4xl mx-auto p-6 bg-white shadow-md rounded-lg">
      <h1 className="text-3xl font-bold mb-4">Terms and Conditions</h1>
      <p className="text-sm text-gray-500 mb-6">Last Updated: 25-09-2025</p>

      <p className="mb-4">
        Welcome to <strong>trackscop.com</strong>. By accessing or using our
        platform (“Service”), you agree to comply with and be bound by the
        following Terms and Conditions. Please read them carefully.
      </p>

      <section className="mb-6">
        <h2 className="text-xl font-semibold mb-2">1. Use of the Service</h2>
        <ul className="list-disc list-inside space-y-2">
          <li>
            Our tool is designed to provide reporting and analytics for SEO, PPC,
            and social media campaigns.
          </li>
          <li>
            You are responsible for ensuring the accuracy of the data you input
            and for maintaining compliance with the advertising policies of
            third-party platforms (Google, Meta, LinkedIn, etc.).
          </li>
          <li>
            You agree not to misuse, resell, or exploit the Service in any
            unlawful manner.
          </li>
        </ul>
      </section>

      <section className="mb-6">
        <h2 className="text-xl font-semibold mb-2">2. Account Registration</h2>
        <ul className="list-disc list-inside space-y-2">
          <li>You must provide accurate and complete information during sign-up.</li>
          <li>You are responsible for maintaining the confidentiality of your login credentials.</li>
        </ul>
      </section>

      <section className="mb-6">
        <h2 className="text-xl font-semibold mb-2">3. Subscription & Payments</h2>
        <ul className="list-disc list-inside space-y-2">
          <li>Certain features may require a paid subscription.</li>
          <li>All fees are non-refundable unless otherwise stated.</li>
        </ul>
      </section>

      <section className="mb-6">
        <h2 className="text-xl font-semibold mb-2">4. Third-Party Integrations</h2>
        <ul className="list-disc list-inside space-y-2">
          <li>The Service may integrate with third-party platforms (Google Ads, Facebook Ads, etc.).</li>
          <li>We are not responsible for the performance, availability, or policies of these third-party services.</li>
        </ul>
      </section>

      <section className="mb-6">
        <h2 className="text-xl font-semibold mb-2">5. Data & Reporting</h2>
        <ul className="list-disc list-inside space-y-2">
          <li>Reports generated by the Service are based on data collected from third-party platforms and may contain errors or delays outside of our control.</li>
          <li>We provide insights for informational purposes only and do not guarantee marketing outcomes.</li>
        </ul>
      </section>

      <section className="mb-6">
        <h2 className="text-xl font-semibold mb-2">6. Intellectual Property</h2>
        <ul className="list-disc list-inside space-y-2">
          <li>All software, content, and materials provided remain the property of <a href="https://trackscop.com" className="text-blue-600 underline">trackscop.com</a>.</li>
          <li>You may not copy, distribute, or reverse-engineer our platform.</li>
        </ul>
      </section>

      <section className="mb-6">
        <h2 className="text-xl font-semibold mb-2">7. Limitation of Liability</h2>
        <ul className="list-disc list-inside space-y-2">
          <li>We are not liable for any loss of data, revenue, or business resulting from the use of the Service.</li>
          <li>The Service is provided “as is” without warranties of any kind.</li>
        </ul>
      </section>

      <section className="mb-6">
        <h2 className="text-xl font-semibold mb-2">8. Termination</h2>
        <p>We may suspend or terminate your account if you violate these Terms.</p>
      </section>
    </div>
  );
};

export default TermsAndConditions;
