import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner"
import Loader from "@/components/global/Loader";
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import ReactQueryProvider from "@/components/ReactQueryProvider";

// Create a React Query client instance
const queryClient = new QueryClient();

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Loader />
          <ReactQueryProvider>
          {/* {children} */}
        {children}
        </ReactQueryProvider>
        <Toaster />
        
      </body>
    </html>
  );
}
