import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import Loader from "@/components/global/Loader";

import ReactQueryProvider from "@/components/ReactQueryProvider";
import { Poppins } from "next/font/google";
import { CampaignDataProvider } from "@/app/context/CampaignContext";



const poppins = Poppins({
  subsets: ["latin"],
  weight: "400",
});


export const metadata: Metadata = {
  title: "Seo-dashBoard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased  relative `}>
       
        <CampaignDataProvider>
          <Loader />
          <ReactQueryProvider>
         
            {children}
          </ReactQueryProvider>
          <Toaster />
        </CampaignDataProvider>
      </body>
    </html>
  );
}
